name: Deploy to FTP

on:
  push:
    branches:
      - main  # Jalankan workflow setiap kali ada push ke branch "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Mengunci versi runner ke ubuntu-22.04
    steps:
      # Checkout kode dari repository GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Upload file ke FTP server
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0  # Menggunakan versi v4.3.0
        with:
          server: "145.223.108.104"  # IP server FTP Anda
          username: "u741610542"     # Username FTP Anda
          password: ${{ secrets.FTP_PASSWORD }}  # Password FTP diatur sebagai secret
          local-dir: "./"            # Direktori lokal (proyek Anda)
          server-dir: "/domains/smantap.com/public_html"  # Path direktori di server